version: '3.8'

services:
  broker1:
    build:
      context: .
      dockerfile: Dockerfile.broker
    command: -id=broker1 -porta=8080 -lider=true
    ports:
      - "8080:8080"
    networks:
      - raft-network
    environment:
      - RAFT_NODE_ID=broker1
      - RAFT_ADDRESS=broker1:8080

  broker2:
    build:
      context: .
      dockerfile: Dockerfile.broker
    command: -id=broker2 -porta=8081 -lider=false
    ports:
      - "8081:8081"
    networks:
      - raft-network
    depends_on:
      - broker1
    environment:
      - RAFT_NODE_ID=broker2
      - RAFT_ADDRESS=broker2:8081
      - RAFT_LEADER_ADDRESS=broker1:8080

  broker3:
    build:
      context: .
      dockerfile: Dockerfile.broker
    command: -id=broker3 -porta=8082 -lider=false
    ports:
      - "8082:8082"
    networks:
      - raft-network
    depends_on:
      - broker1
    environment:
      - RAFT_NODE_ID=broker3
      - RAFT_ADDRESS=broker3:8082
      - RAFT_LEADER_ADDRESS=broker1:8080

networks:
  raft-network:
    driver: bridge